import {
  ArrowLeft,
  ArrowRight,
  BarChart2,
  Calendar,
  CalendarCheck,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Contact,
  Home,
  Layout,
  LayoutList,
  LifeBuoy,
  LogOut,
  Menu,
  Plus,
  Settings,
  Users,
  X,
  type Icon as LucideIcon,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  add: Plus,
  analytics: BarChart2,
  arrow: { left: ArrowLeft, right: ArrowRight },
  calendar: { appointment: CalendarCheck, date: Calendar },
  check: Check,
  checkCircle: CheckCircle,
  chevron: { down: ChevronDown, left: ChevronLeft, right: ChevronRight },
  clients: Contact,
  close: X,
  home: Home,
  hour: Clock,
  help: LifeBuoy,
  layout: Layout,
  logout: LogOut,
  menu: Menu,
  service: LayoutList,
  settings: Settings,
  staff: Users,
}
